### ISSUE TITLE
Docker images not avalible ?

### ISSUE THREAD

**Issue by masterwishx** [hyp3rd/telegram-discord-bridge#36]
https://github.com/hyp3rd/telegram-discord-bridge/pkgs/container/bridge 
ghcr.io/hyp3rd/bridge:v1.1.9
got 404 error

**Comment by hyp3rd** [comment]
Hello there, it's a broken link in the README. 

You can checkout the images here at the [package page](
https://github.com/hyp3rd/telegram-discord-bridge/pkgs/container/bridge).
