### ISSUE TITLE
Unable to get MFA-Code via API, docker healthcheck failing

### ISSUE THREAD

**Issue by lokipo** [hyp3rd/telegram-discord-bridge#39]
Hi,

I was able to get your docker-container running but have 2 issues I cannot get around.

1. Getting the MFA-code via Api ist not working, the bridge simply waits for the API to return the (properly generated) telegram-MFA-code, that is it. If I disable the API via "telegram_login_enabled: False" and enter the code myself, everything works. Of course I do have to run the bridge in the foreground then an suspend it via ctrl-z. Not the best solution to have the container restarted automatically. Cannot figure out as to what I am missing.
2. The docker healthcheck fails with a 405 error. This might be due to me having disabled the API while trying to get around the MFA issue.

Any suggestions?

Thank you,

Tilman

**Comment by hyp3rd** [comment]
Hey there, 

The API is not ready yet, still in dev, so keep that in mind. Is the reason why it needs to be fully documented, or not documented at all.

That being said, yes, the bridge is there waiting, and there is an endpoint you need to hit after starting it:

Send a POST request to `http://127.0.0.1:8000/api/v1/bridge/` to start the process:

Send a POST request afterwards to `http://127.0.0.1:8000/api/v1/auth/telegram` with the following payload to complete the authentication:

```json
{
	"code": 123456,
        "password": "password"
}
```

Where `code` (integer) is the one you get from Telegram, and `password` is your 2FA if enabled. If you don't have the 2FA set, send an empty string.

**Comment by lokipo** [comment]
Brilliant. Thank you!
