### ISSUE TITLE
Duplicate messages forwarded

### ISSUE THREAD

**Issue by DaCaemboe** [hyp3rd/telegram-discord-bridge#47]
Sometimes users spam the same message and they all get forwarded to discord.

How do I block duplicate messages from being sent?

I tried using an if/else statement for duplicate messages, but the script doesn't do anything when I apply those changes.
Any chance you can help me with this?

```
global last_message

async def process_message_text(event, forwarder_config: dict[str, Any],
                               mention_everyone: bool,
                               mention_roles: List[str],
                               openai_enabled: bool) -> str:  # pylint: disable=too-many-arguments
    """Process the message text and return the processed text."""
    message_text = event.message.message

    if last_message != message_text:

        if openai_enabled:
            suggestions = await analyze_message_sentiment(message_text)
            message_text = f'{message_text}\n{suggestions}'

        if mention_everyone:
            message_text += '\n' + '@everyone'

        if mention_roles:
            mention_text = ", ".join(role for role in mention_roles)
            message_text = f"{mention_text}\n{message_text}"

        last_message = message_text

        return telegram_entities_to_markdown(message_text, event.message.entities,
                                             forwarder_config["strip_off_links"])
    else:
        print("\n========================================\nDENIED MESSAGE\n========================================\n  Duplicate Last Message, Ignoring \n========================================\nDENIED MESSAGE\n========================================\n")

    last_message = message_text
```

**Comment by DaCaemboe** [comment]
Also, when a # or @ (user tagged) is added to the text it seems to strip off characters like dashes and double colons and also the spaces around those characters.

**Comment by hyp3rd** [comment]
Catching duplicate messages is a little tricky. But I'll check it out. I'm about to push a significant change for the whole codebase in the next days, then I'll pick it up this issue.

**Comment by DaCaemboe** [comment]
sounds great!
any solution for the output fix?

I see that you filter out hashtags and dashes when a hashtag is found in the text, but it messes up some stuff. any workaround to leave the output text as is?

**Comment by hyp3rd** [comment]
I'm pushing today the change with an optional anti-spam filter.
For now is very basic, but it detects duplicates. That should do for your case. Once I finish the API I will add more features to it
