### ISSUE TITLE
Underscores are stripped from links.

### ISSUE THREAD

**Issue by lokipo** [hyp3rd/telegram-discord-bridge#60]
**Describe the bug**
If the script forwards a link from telegram to discord the underscore ("_") and maybe other special characters are stripped.

**To Reproduce**
Forward a link like "https://example.com/discord_telegram" and watch it become "https://example.com/discordtelegram"

**Expected behavior**
The link being forwarded as is.

**Comment by hyp3rd** [comment]
Hello, I'm not able to reproduce it with my settings. Would you share your forwarders configuration?
The links with dashes or underscores are forwarded correctly as far as I'm concerned.

**Comment by lokipo** [comment]
Hi, just updated my container, due to some utter stupidity I pulled version 1.1.1. Maybe this is why. Will update as soon as the next link is being forwarded.

Sorry for the inconvenience!

**Comment by lokipo** [comment]
Sure enough, using the latest version (1.2.3) fixes the bug right away.
